"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VueI18nInstance = exports.VueI18n = exports.writeIndexFile = exports.replaceVueTemplate = exports.replaceVueScript = exports.replaceJavaScript = exports.warnlog = exports.successlog = exports.errorlog = void 0;
var utils_1 = require("./utils");
Object.defineProperty(exports, "errorlog", { enumerable: true, get: function () { return utils_1.errorlog; } });
Object.defineProperty(exports, "successlog", { enumerable: true, get: function () { return utils_1.successlog; } });
Object.defineProperty(exports, "warnlog", { enumerable: true, get: function () { return utils_1.warnlog; } });
Object.defineProperty(exports, "replaceJavaScript", { enumerable: true, get: function () { return utils_1.replaceJavaScript; } });
Object.defineProperty(exports, "replaceVueScript", { enumerable: true, get: function () { return utils_1.replaceVueScript; } });
Object.defineProperty(exports, "replaceVueTemplate", { enumerable: true, get: function () { return utils_1.replaceVueTemplate; } });
Object.defineProperty(exports, "writeIndexFile", { enumerable: true, get: function () { return utils_1.writeIndexFile; } });
var i18nFile_1 = require("./i18nFile");
exports.VueI18n = i18nFile_1.default;
Object.defineProperty(exports, "VueI18nInstance", { enumerable: true, get: function () { return i18nFile_1.VueI18nInstance; } });
