"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VueI18nInstance = exports.VueI18n = exports.warnlog = exports.successlog = exports.errorlog = exports.recoverVueScript = exports.recoverJavaScriptFile = exports.recoverJavaScript = exports.replaceJavaScript = exports.replaceVueScript = exports.replaceJavaScriptFile = exports.replaceVueTemplate = void 0;
var utils_1 = require("./utils");
Object.defineProperty(exports, "errorlog", { enumerable: true, get: function () { return utils_1.errorlog; } });
Object.defineProperty(exports, "successlog", { enumerable: true, get: function () { return utils_1.successlog; } });
Object.defineProperty(exports, "warnlog", { enumerable: true, get: function () { return utils_1.warnlog; } });
var i18nFile_1 = require("./core/i18nFile");
exports.VueI18n = i18nFile_1.default;
Object.defineProperty(exports, "VueI18nInstance", { enumerable: true, get: function () { return i18nFile_1.VueI18nInstance; } });
var replaceVueTemplate_1 = require("./core/replaceVueTemplate");
exports.replaceVueTemplate = replaceVueTemplate_1.default;
var replaceJavaScript_1 = require("./core/replaceJavaScript");
exports.replaceJavaScript = replaceJavaScript_1.default;
var transform_1 = require("./core/transform");
Object.defineProperty(exports, "replaceJavaScriptFile", { enumerable: true, get: function () { return transform_1.replaceJavaScriptFile; } });
Object.defineProperty(exports, "replaceVueScript", { enumerable: true, get: function () { return transform_1.replaceVueScript; } });
var recoverJavaScript_1 = require("./core/recoverJavaScript");
exports.recoverJavaScript = recoverJavaScript_1.default;
var recover_1 = require("./core/recover");
Object.defineProperty(exports, "recoverJavaScriptFile", { enumerable: true, get: function () { return recover_1.recoverJavaScriptFile; } });
Object.defineProperty(exports, "recoverVueScript", { enumerable: true, get: function () { return recover_1.recoverVueScript; } });
